// Placeholder catalogue and contact data.
// Replace the package names, pricing, contact numbers, and testimonials with the confirmed Family Health Plus content when available.

export const CONTACT = {
  phoneDisplay: '+91 90000 00000',
  phoneHref: 'tel:+919000000000',
  whatsappDisplay: '+91 90000 00000',
  whatsappHref: 'https://wa.me/919000000000?text=Hi%20Family%20Health%20Plus,%20I%20want%20to%20book%20a%20health%20checkup.',
  email: 'hello@familyhealthplus.in',
  emailHref: 'mailto:hello@familyhealthplus.in',
  location: 'Hyderabad, Telangana',
  address: 'Family Health Plus, Hyderabad, Telangana',
  reportsHref: '#reports',
  loginHref: '#login',
};

export const NAV_LINKS = [
  { label: 'Home', href: '#home' },
  { label: 'Health Packages', href: '#packages' },
  { label: 'Lab Tests', href: '#services' },
  { label: 'Men', href: '#tab-men' },
  { label: 'Women', href: '#tab-women' },
  { label: 'Couple', href: '#tab-couple' },
  { label: 'Family', href: '#tab-family' },
  { label: 'Senior Citizen', href: '#tab-senior' },
  { label: 'Corporate Checkup', href: '#corporate' },
  { label: 'Home Sample Collection', href: '#home-collection' },
  { label: 'About Us', href: '#about' },
  { label: 'Contact Us', href: '#contact' },
];

export const QUICK_LINKS = [
  { label: 'About', href: '#about' },
  { label: 'Offers', href: '#offers' },
  { label: 'Reports', href: CONTACT.reportsHref },
  { label: 'Login', href: CONTACT.loginHref },
];

export const TRUST_BADGES = [
  'Certified Labs',
  'Home Sample Collection',
  'Accurate Reports',
  'Expert Consultation',
  'Affordable Packages',
];

export const HERO_METRICS = [
  { value: '4', suffix: '', label: 'simple booking steps' },
  { value: '8', suffix: '+', label: 'service families' },
  { value: '12', suffix: '+', label: 'trust signals' },
];

export const PACKAGE_TABS = [
  { key: 'couple', label: 'Couple' },
  { key: 'men', label: 'Men' },
  { key: 'women', label: 'Women' },
  { key: 'family', label: 'Family' },
  { key: 'senior', label: 'Senior Citizen' },
  { key: 'fullBody', label: 'Full Body Checkup' },
  { key: 'corporate', label: 'Corporate' },
  { key: 'home', label: 'Home Collection' },
];

const buildPackage = ({
  category,
  slug,
  name,
  tests,
  price,
  discount,
  summary,
  included,
  prep,
  who,
  report,
  homeSample,
  badge,
}) => ({
  category,
  slug,
  name,
  tests,
  price,
  discount,
  summary,
  included,
  prep,
  who,
  report,
  homeSample,
  badge,
});

export const PACKAGE_GROUPS = {
  couple: [
    buildPackage({
      category: 'couple',
      slug: 'harmony-couple-checkup',
      name: 'Harmony Couple Checkup',
      tests: '150 tests',
      price: '₹4,999*',
      discount: '₹2,999*',
      summary: 'Balanced preventive screening for two adults planning ahead together.',
      included: ['Blood profile', 'Heart markers', 'Vitamin screening'],
      prep: 'Fasting may be required for selected blood tests. Confirm on booking.',
      who: 'Ideal for couples who want a shared annual wellness baseline.',
      report: '24 to 48 hours',
      homeSample: true,
      badge: 'Popular',
    }),
    buildPackage({
      category: 'couple',
      slug: 'prime-couple-checkup',
      name: 'Prime Couple Checkup',
      tests: '128 tests',
      price: '₹4,299*',
      discount: '₹2,599*',
      summary: 'A practical preventive package with broad organ and lifestyle markers.',
      included: ['Kidney function', 'Liver panel', 'Diabetes markers'],
      prep: 'Please share medication details before the sample visit.',
      who: 'Useful for couples looking for a strong health checkpoint without excess noise.',
      report: 'Same day to 24 hours',
      homeSample: true,
      badge: 'Recommended',
    }),
    buildPackage({
      category: 'couple',
      slug: 'essential-couple-screening',
      name: 'Essential Couple Screening',
      tests: '102 tests',
      price: '₹3,499*',
      discount: '₹1,999*',
      summary: 'A lighter entry-level option for first-time preventive health booking.',
      included: ['CBC', 'Blood sugar', 'Urine routine'],
      prep: 'Hydration is fine, but follow fasting guidance if advised at booking.',
      who: 'Good for first-time users who want a simple and clear preventive step.',
      report: '24 hours',
      homeSample: true,
      badge: '',
    }),
  ],
  men: [
    buildPackage({
      category: 'men',
      slug: 'momentum-men-checkup',
      name: 'Momentum Men Checkup',
      tests: '142 tests',
      price: '₹4,499*',
      discount: '₹2,699*',
      summary: 'Focuses on lifestyle, liver, cardiac, and metabolic markers for men.',
      included: ['Liver health', 'Heart markers', 'Glucose profile'],
      prep: 'Fasting is usually recommended for the blood panel.',
      who: 'For men wanting a strong all-round preventive screen.',
      report: '24 to 48 hours',
      homeSample: true,
      badge: 'Popular',
    }),
    buildPackage({
      category: 'men',
      slug: 'cardio-focus-men',
      name: 'Cardio Focus Men',
      tests: '116 tests',
      price: '₹3,999*',
      discount: '₹2,399*',
      summary: 'A practical cardiovascular and metabolic focus package.',
      included: ['ECG', 'Lipid profile', 'Blood pressure review'],
      prep: 'Share previous cardiac history when you book.',
      who: 'Best for men who want a heart-first preventive review.',
      report: 'Same day to 24 hours',
      homeSample: true,
      badge: 'Recommended',
    }),
    buildPackage({
      category: 'men',
      slug: 'fitness-liver-men',
      name: 'Fitness and Liver Men',
      tests: '94 tests',
      price: '₹2,999*',
      discount: '₹1,799*',
      summary: 'A streamlined package for fitness-oriented health tracking.',
      included: ['Liver profile', 'Thyroid check', 'Urine analysis'],
      prep: 'Keep the routine light before the sample visit.',
      who: 'Good for active users who want a quick yearly checkpoint.',
      report: '24 hours',
      homeSample: true,
      badge: '',
    }),
  ],
  women: [
    buildPackage({
      category: 'women',
      slug: 'grace-women-checkup',
      name: 'Grace Women Checkup',
      tests: '148 tests',
      price: '₹4,799*',
      discount: '₹2,899*',
      summary: 'A broad women-focused preventive package with hormonal and vitamin checks.',
      included: ['Vitamin profile', 'Hormonal markers', 'Iron studies'],
      prep: 'Share cycle-related details if relevant for your chosen tests.',
      who: 'For women seeking a complete routine health review.',
      report: '24 to 48 hours',
      homeSample: true,
      badge: 'Popular',
    }),
    buildPackage({
      category: 'women',
      slug: 'wellness-women-screening',
      name: 'Wellness Women Screening',
      tests: '121 tests',
      price: '₹3,999*',
      discount: '₹2,299*',
      summary: 'Balanced preventive screening with focus on daily wellness markers.',
      included: ['CBC', 'Thyroid profile', 'Kidney function'],
      prep: 'Fasting may be advised for some components.',
      who: 'Ideal for annual wellness follow-up and family planning stages.',
      report: '24 hours',
      homeSample: true,
      badge: 'Recommended',
    }),
    buildPackage({
      category: 'women',
      slug: 'hormone-vitamin-women',
      name: 'Hormone and Vitamin Women',
      tests: '96 tests',
      price: '₹3,199*',
      discount: '₹1,899*',
      summary: 'A lighter package centred on vitamin, iron, and endocrine balance.',
      included: ['Vitamin B12', 'Vitamin D', 'Hormone panel'],
      prep: 'Bring any recent supplements list to the sample appointment.',
      who: 'Great for targeted monitoring with minimal friction.',
      report: '24 hours',
      homeSample: true,
      badge: '',
    }),
  ],
  family: [
    buildPackage({
      category: 'family',
      slug: 'everyday-family-checkup',
      name: 'Everyday Family Checkup',
      tests: '144 tests',
      price: '₹4,999*',
      discount: '₹2,999*',
      summary: 'A practical all-age preventive package for shared family care.',
      included: ['Blood profile', 'Diabetes screening', 'Organ function'],
      prep: 'Fasting helps standardise the blood test results.',
      who: 'For families who want one booking for the entire household.',
      report: '24 to 48 hours',
      homeSample: true,
      badge: 'Popular',
    }),
    buildPackage({
      category: 'family',
      slug: 'family-care-plus',
      name: 'Family Care Plus',
      tests: '132 tests',
      price: '₹4,199*',
      discount: '₹2,499*',
      summary: 'A focused package for family health tracking and early intervention.',
      included: ['Liver health', 'Heart markers', 'Thyroid check'],
      prep: 'Discuss fasting and medication instructions at booking time.',
      who: 'Suitable for families who want a dependable yearly baseline.',
      report: '24 hours',
      homeSample: true,
      badge: 'Recommended',
    }),
    buildPackage({
      category: 'family',
      slug: 'family-shield-screening',
      name: 'Family Shield Screening',
      tests: '108 tests',
      price: '₹3,599*',
      discount: '₹2,099*',
      summary: 'Lightweight family screening built for a quick annual check-in.',
      included: ['CBC', 'Urine analysis', 'Sugar profile'],
      prep: 'Keep the morning schedule flexible if fasting is required.',
      who: 'Best for families who prefer an easier, lower-friction screen.',
      report: 'Same day to 24 hours',
      homeSample: true,
      badge: '',
    }),
  ],
  senior: [
    buildPackage({
      category: 'senior',
      slug: 'golden-years-checkup',
      name: 'Golden Years Checkup',
      tests: '152 tests',
      price: '₹4,999*',
      discount: '₹2,999*',
      summary: 'Tailored for older adults with bone, heart, and metabolic focus.',
      included: ['Bone health', 'Cardiac markers', 'Kidney profile'],
      prep: 'Share medication details and mobility support needs in advance.',
      who: 'For senior citizens needing a careful and complete check.',
      report: '24 to 48 hours',
      homeSample: true,
      badge: 'Recommended',
    }),
    buildPackage({
      category: 'senior',
      slug: 'senior-heart-bone',
      name: 'Senior Heart and Bone',
      tests: '126 tests',
      price: '₹4,199*',
      discount: '₹2,499*',
      summary: 'A focused package for circulatory and skeletal wellness.',
      included: ['ECG', 'Vitamin D', 'Calcium profile'],
      prep: 'A companion can assist during the sample collection if needed.',
      who: 'Useful when heart and mobility are the main concerns.',
      report: '24 hours',
      homeSample: true,
      badge: 'Popular',
    }),
    buildPackage({
      category: 'senior',
      slug: 'senior-comfort-screening',
      name: 'Senior Comfort Screening',
      tests: '98 tests',
      price: '₹3,199*',
      discount: '₹1,899*',
      summary: 'A simpler senior package for routine observation and follow-up.',
      included: ['CBC', 'Sugar profile', 'Liver panel'],
      prep: 'Use this for easy annual screening or after a doctor visit.',
      who: 'Good for seniors who want a lighter preventive option.',
      report: 'Same day to 24 hours',
      homeSample: true,
      badge: '',
    }),
  ],
  fullBody: [
    buildPackage({
      category: 'fullBody',
      slug: 'advance-full-body',
      name: 'Advance Full Body',
      tests: '156 tests',
      price: '₹5,499*',
      discount: '₹3,299*',
      summary: 'A broad full body wellness package with extra diagnostic depth.',
      included: ['Heart profile', 'Liver and kidney', 'Thyroid check'],
      prep: 'Fasting is usually required for the most accurate results.',
      who: 'For users who want a deeper annual health inventory.',
      report: '24 to 48 hours',
      homeSample: true,
      badge: 'Popular',
    }),
    buildPackage({
      category: 'fullBody',
      slug: 'executive-full-body',
      name: 'Executive Full Body',
      tests: '132 tests',
      price: '₹4,699*',
      discount: '₹2,799*',
      summary: 'A balanced full body package for busy professionals.',
      included: ['Lipid profile', 'Kidney function', 'Liver health'],
      prep: 'Keep your schedule flexible for the early morning sample slot.',
      who: 'Ideal for annual corporate-style wellness checks.',
      report: '24 hours',
      homeSample: true,
      badge: 'Recommended',
    }),
    buildPackage({
      category: 'fullBody',
      slug: 'complete-wellness',
      name: 'Complete Wellness',
      tests: '114 tests',
      price: '₹3,799*',
      discount: '₹2,299*',
      summary: 'A clear starting point for comprehensive preventive health.',
      included: ['CBC', 'Sugar profile', 'Urine analysis'],
      prep: 'A simple fasting window improves standardisation.',
      who: 'For users who want a dependable full-body baseline.',
      report: 'Same day to 24 hours',
      homeSample: true,
      badge: '',
    }),
  ],
  corporate: [
    buildPackage({
      category: 'corporate',
      slug: 'employee-wellness-basic',
      name: 'Employee Wellness Basic',
      tests: '96 tests',
      price: 'Custom quote',
      discount: 'Volume pricing',
      summary: 'Entry package for teams that want routine employee health support.',
      included: ['CBC', 'Sugar profile', 'Vitals review'],
      prep: 'Bulk scheduling can be aligned with your work shifts.',
      who: 'For small teams and startups launching a wellness program.',
      report: '24 to 48 hours',
      homeSample: false,
      badge: 'Corporate',
    }),
    buildPackage({
      category: 'corporate',
      slug: 'executive-onsite-screening',
      name: 'Executive On-site Screening',
      tests: '126 tests',
      price: 'Custom quote',
      discount: 'Volume pricing',
      summary: 'On-site health checks built for leadership and office teams.',
      included: ['Heart review', 'Liver profile', 'Risk assessment'],
      prep: 'On-site sample flow can be scheduled for one or multiple teams.',
      who: 'For organisations that want a more premium onsite experience.',
      report: '24 hours',
      homeSample: false,
      badge: 'Popular',
    }),
    buildPackage({
      category: 'corporate',
      slug: 'custom-team-programs',
      name: 'Custom Team Programs',
      tests: 'Flexible',
      price: 'Custom quote',
      discount: 'Tailored scope',
      summary: 'Bespoke health-check design based on role, shift, and risk profile.',
      included: ['Role-specific tests', 'Wellness brief', 'Report review'],
      prep: 'We can align the test plan with policy and HR guidelines.',
      who: 'For HR teams seeking a configurable annual health benefit.',
      report: 'Custom schedule',
      homeSample: true,
      badge: 'Custom',
    }),
  ],
  home: [
    buildPackage({
      category: 'home',
      slug: 'home-test-essentials',
      name: 'Home Test Essentials',
      tests: '84 tests',
      price: '₹2,799*',
      discount: '₹1,699*',
      summary: 'At-home collection for routine tests with minimal effort.',
      included: ['CBC', 'Sugar profile', 'Urine analysis'],
      prep: 'Use a comfortable fasting window if requested by the package.',
      who: 'For users who want the convenience of sample collection at home.',
      report: 'Same day to 24 hours',
      homeSample: true,
      badge: 'Popular',
    }),
    buildPackage({
      category: 'home',
      slug: 'fasting-blood-profile',
      name: 'Fasting Blood Profile',
      tests: '58 tests',
      price: '₹1,999*',
      discount: '₹1,299*',
      summary: 'A compact at-home fasting panel for regular monitoring.',
      included: ['Blood sugar', 'Lipid profile', 'Liver profile'],
      prep: 'Fasting is required for the best sample quality.',
      who: 'Good for users who prefer a quick blood-only panel.',
      report: '24 hours',
      homeSample: true,
      badge: 'Recommended',
    }),
    buildPackage({
      category: 'home',
      slug: 'at-home-health-snapshot',
      name: 'At-Home Health Snapshot',
      tests: '76 tests',
      price: '₹2,499*',
      discount: '₹1,499*',
      summary: 'A broad home collection option for a clear wellness snapshot.',
      included: ['CBC', 'Thyroid check', 'Kidney function'],
      prep: 'A short pre-test note will confirm the right fasting window.',
      who: 'Useful for people balancing convenience with breadth.',
      report: '24 to 48 hours',
      homeSample: true,
      badge: '',
    }),
  ],
};

export const PACKAGE_BOOKING_OPTIONS = [
  'Choose a package',
  'Health Packages',
  'Men',
  'Women',
  'Couple',
  'Family',
  'Senior Citizen',
  'Full Body Checkup',
  'Corporate Checkup',
  'Home Sample Collection',
  'Lab Tests',
  'Doctor Consultation',
  'Report Review',
];

export const SERVICE_CARDS = [
  {
    icon: '🩺',
    title: 'Preventive Health Checkup',
    text: 'Structured screenings for everyday health tracking and early action.',
  },
  {
    icon: '🧪',
    title: 'Lab Tests',
    text: 'Focused blood and diagnostic tests with simple booking and quick reporting.',
  },
  {
    icon: '💓',
    title: 'Heart Health Checkup',
    text: 'Cardiac-focused screening built around lifestyle and risk markers.',
  },
  {
    icon: '🧬',
    title: 'Diabetes Checkup',
    text: 'Glucose and metabolic reviews for better long-term monitoring.',
  },
  {
    icon: '🌿',
    title: 'Women\'s Health Checkup',
    text: 'Health checks shaped around iron, hormone, and general wellness needs.',
  },
  {
    icon: '🧓',
    title: 'Senior Citizen Checkup',
    text: 'Thoughtful packages for older adults with gentler sample workflows.',
  },
  {
    icon: '👨‍👩‍👧‍👦',
    title: 'Family Health Checkup',
    text: 'One booking for the household with easier coordination and shared support.',
  },
  {
    icon: '🏢',
    title: 'Corporate Health Checkup',
    text: 'Bulk and onsite health programs for teams, offices, and leadership groups.',
  },
  {
    icon: '🏠',
    title: 'Home Sample Collection',
    text: 'Sample pickup that reduces friction for busy families and senior patients.',
  },
  {
    icon: '👩‍⚕️',
    title: 'Doctor Consultation',
    text: 'Optional clinician review to help users interpret next steps clearly.',
  },
  {
    icon: '📋',
    title: 'Report Review',
    text: 'Simple report follow-up for users who need a clearer explanation.',
  },
];

export const WHY_US = [
  { value: 8, suffix: '+', label: 'service pillars' },
  { value: 4, suffix: '', label: 'booking steps' },
  { value: 12, suffix: '+', label: 'trust signals' },
  { value: 24, suffix: '/7', label: 'helpful support style' },
];

export const WHY_POINTS = [
  'Accurate reports',
  'Trusted healthcare partner',
  'Experienced team',
  'Home sample collection',
  'Affordable packages',
  'Fast report delivery',
  'Modern lab standards',
  'Easy online booking',
];

export const HOW_IT_WORKS = [
  {
    step: '01',
    title: 'Pick a package',
    text: 'Use the tabs to compare family, couple, senior, and corporate options.',
  },
  {
    step: '02',
    title: 'Book online or request a callback',
    text: 'Send your details once and we will confirm the best slot for you.',
  },
  {
    step: '03',
    title: 'Home collection or centre visit',
    text: 'Choose the most convenient sample flow for your schedule.',
  },
  {
    step: '04',
    title: 'Get reports and guidance',
    text: 'Review the report and ask for a clear explanation of the next steps.',
  },
];

export const TESTIMONIALS = [
  {
    quote: 'The booking flow felt calm and easy, and the callback was quick.',
    name: 'Priya N.',
    location: 'Hyderabad',
    note: 'Replace with real testimonial.',
  },
  {
    quote: 'Home sample collection made the whole process much simpler for our family.',
    name: 'Rohit S.',
    location: 'Secunderabad',
    note: 'Replace with real testimonial.',
  },
  {
    quote: 'The packages are organised well, so it was easy to compare options.',
    name: 'Ananya M.',
    location: 'Bengaluru',
    note: 'Replace with real testimonial.',
  },
];

export const FAQS = [
  {
    question: 'What is included in a full body checkup?',
    answer: 'It usually includes a broad mix of blood tests, organ markers, and preventive screening components. The exact mix depends on the package you choose.',
  },
  {
    question: 'Can I book home sample collection?',
    answer: 'Yes. Most package cards in this build show home collection availability, and the booking form includes that option.',
  },
  {
    question: 'How will I receive my reports?',
    answer: 'Reports can be shared digitally. If a CRM or report portal is connected later, this can link into a secure delivery flow.',
  },
  {
    question: 'Do I need fasting before tests?',
    answer: 'Some packages require fasting while others do not. The package details and booking note should confirm this before collection.',
  },
  {
    question: 'How do I choose the right package?',
    answer: 'Start with your age group, family needs, and whether you prefer home collection. If unsure, request a callback and compare the recommended options.',
  },
  {
    question: 'Are corporate health checkups available?',
    answer: 'Yes. The corporate section supports both bulk screening and custom onsite plans for teams.',
  },
];

export const FOOTER_COLUMNS = [
  {
    title: 'Health Packages',
    links: [
      { label: 'Couple', href: '#tab-couple' },
      { label: 'Men', href: '#tab-men' },
      { label: 'Women', href: '#tab-women' },
      { label: 'Family', href: '#tab-family' },
      { label: 'Senior Citizen', href: '#tab-senior' },
    ],
  },
  {
    title: 'Lab Tests',
    links: [
      { label: 'Blood Tests', href: '#services' },
      { label: 'Heart Health', href: '#services' },
      { label: 'Diabetes Checkup', href: '#services' },
      { label: 'Report Review', href: '#services' },
      { label: 'Home Collection', href: '#home-collection' },
    ],
  },
  {
    title: 'Company',
    links: [
      { label: 'About Us', href: '#about' },
      { label: 'Corporate Checkup', href: '#corporate' },
      { label: 'Contact Us', href: '#contact' },
      { label: 'Privacy Policy', href: '#privacy' },
      { label: 'Terms & Conditions', href: '#terms' },
      { label: 'Refund Policy', href: '#refund' },
    ],
  },
];

export const SOCIAL_LINKS = [
  { label: 'Instagram', href: '#instagram' },
  { label: 'Facebook', href: '#facebook' },
  { label: 'LinkedIn', href: '#linkedin' },
  { label: 'YouTube', href: '#youtube' },
];

export const SITE_SCHEMA = {
  '@context': 'https://schema.org',
  '@type': 'MedicalBusiness',
  name: 'Family Health Plus',
  url: 'https://www.familyhealthplus.in/',
  description: 'Preventive health checkups, lab tests, home sample collection, and corporate health screening.',
  areaServed: 'India',
};